# Generated by Django 3.2.5 on 2021-08-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogplant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogplant',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=264, unique=True),
        ),
    ]
