# Generated by Django 3.2.5 on 2021-09-28 03:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('description', models.TextField()),
                ('availablity', models.BooleanField(default=False)),
                ('shippingCharges', models.IntegerField(default=0)),
                ('offers', models.IntegerField(default=0)),
                ('plantingAndCare', models.TextField()),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratingCount', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('ratingValue', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catName', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonName', models.TextField(default='', max_length=50)),
                ('plantSpread', models.TextField(default='', max_length=50)),
                ('maxHeight', models.TextField(default='', max_length=50)),
                ('sunlight', models.TextField(default='', max_length=50)),
                ('watering', models.TextField(default='', max_length=50)),
                ('soil', models.TextField(default='', max_length=50)),
                ('temp', models.TextField(default='', max_length=50)),
                ('ferti', models.TextField(default='', max_length=50)),
                ('bloomTime', models.TextField(default='', max_length=50)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemmain')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemmain')),
            ],
        ),
        migrations.AddField(
            model_name='itemmain',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemscat'),
        ),
        migrations.CreateModel(
            name='ItemFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('answer', models.TextField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemmain')),
            ],
        ),
    ]
