# Generated by Django 3.2.5 on 2021-09-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmain',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
