# Generated by Django 3.2.5 on 2021-09-28 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_itemmain_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrating',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.itemmain'),
        ),
        migrations.AlterField(
            model_name='itemrating',
            name='ratingValue',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
