# Generated by Django 3.2.5 on 2021-09-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210928_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrating',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.itemmain'),
        ),
    ]
