# Generated by Django 3.2.6 on 2021-10-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_itemrating_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bstates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.DecimalField(decimal_places=0, editable=False, max_digits=16)),
                ('namecard', models.CharField(max_length=264)),
                ('cvv', models.DecimalField(decimal_places=0, editable=False, max_digits=3)),
                ('validity', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sfirst_name', models.CharField(max_length=264)),
                ('Slast_name', models.CharField(max_length=264)),
                ('Sstreet', models.CharField(max_length=264)),
                ('Sapartment', models.CharField(max_length=264)),
                ('Scity', models.CharField(max_length=264)),
                ('Szip', models.DecimalField(decimal_places=0, editable=False, max_digits=6)),
                ('Sphone', models.DecimalField(decimal_places=0, editable=False, max_digits=10)),
                ('Semail', models.EmailField(max_length=264)),
                ('Scheckout_states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sstates', to='products.bstates')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bfirst_name', models.CharField(max_length=264)),
                ('Blast_name', models.CharField(max_length=264)),
                ('Bstreet', models.CharField(max_length=264)),
                ('Bapartment', models.CharField(max_length=264)),
                ('Bcity', models.CharField(max_length=264)),
                ('Bzip', models.DecimalField(decimal_places=0, editable=False, max_digits=6)),
                ('Bphone', models.DecimalField(decimal_places=0, editable=False, max_digits=10)),
                ('Bemail', models.EmailField(max_length=264)),
                ('Bcheckout_states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bstates', to='products.bstates')),
            ],
        ),
    ]
