# Generated by Django 3.2.6 on 2021-10-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_billing_bstates_payment_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='Bphone',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='Bzip',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardno',
            field=models.DecimalField(decimal_places=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='Sphone',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='Szip',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
