# Generated by Django 3.2.5 on 2021-10-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_usercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='Bphone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='billing',
            name='Bzip',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cardno',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cvv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='Sphone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='Szip',
            field=models.IntegerField(default=0),
        ),
    ]
