# Generated by Django 3.2.5 on 2021-10-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211012_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='validity',
            field=models.DateField(default='0000-00'),
        ),
    ]
